package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.LoanInfo;

import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int updateByPrimaryKey(LoanInfo record);

    /**
     * 获取历史平均年化收益
     * @return
     */
    Double selectHistoryAverageRate();

    /**
     * 按类型查找产品
     * @return
     */
    List<LoanInfo> selectProductListByType(Map map);

    /**
     * 获取总记录数
     * @param paramMap
     * @return
     */
    Long selectTotal(Map<String, Object> paramMap);

    /**
     * 根据产品id修改可投资金额
     * @param paramMap
     * @return
     */
    int updateLeftProduceMoneyByLoanId(Map<String, Object> paramMap);

    /**
     * 根据满标状态查找产品
     * @param i 0 未满标  1 已满标  2已发放
     * @return
     */
    List<LoanInfo> selectLoanInfoByStatus(int i);
}