package com.bjpowernode.p2p.mapper.user;

import com.bjpowernode.p2p.model.user.FinanceAccount;

import java.util.HashMap;
import java.util.Map;

public interface FinanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int insert(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int insertSelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    FinanceAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int updateByPrimaryKeySelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Sat May 25 17:27:15 CST 2019
     */
    int updateByPrimaryKey(FinanceAccount record);

    /**
     * 根据用户uid查询余额
     * @param id
     * @return
     */
    FinanceAccount selectFinanceAccountByUid(Integer id);

    /**
     * 根据用户uid修改余额
     * @param paramMap
     * @return
     */
    int updateFinanceAccountByUid(Map<String, Object> paramMap);

    int updateFinanceAccountByIncomeRecord(HashMap<String, Object> paramMap);

    /**
     * 充值金额
     * @param paramMap
     * @return
     */
    int updateFinanceAccountByRecharge(HashMap<String, Object> paramMap);
}